namespace Contoso.Apps.Common
{
    /// <summary>
    /// Contains well-known Name Value Pair properties sent to and returned
    /// from the gateway processor API.
    /// </summary>
    public static class NVPProperties
    {
        /// <summary>
        /// Well-known method names used as values for the METHOD property of the NVP.
        /// </summary>
        public struct Methods
        {
            /// <summary>
            /// Authorize the requested payment amount (first step).
            /// </summary>
            public static string AuthorizePayment = "authpayment";
            /// <summary>
            /// Process the credit card payment (final step).
            /// </summary>
            public static string ProcessPayment = "processpayment";
        }

        /// <summary>
        /// Well-known Name Value Pair properties sent to and returned
        /// from the gateway processor API.
        /// </summary>
        public struct Properties
        {
            /// <summary>
            /// Acknowledgement return value. Possible values: success, successswithwarning, failure.
            /// </summary>
            public static string ACK = "ACK";
            /// <summary>
            /// A token is generated by the processor gateway during the authorization step, and
            /// is used as a refernce to that authorization during the final processing step.
            /// </summary>
            public static string TOKEN = "TOKEN";
            /// <summary>
            /// The method to be performed by the API endpoint.
            /// </summary>
            public static string METHOD = "METHOD";
            /// <summary>
            /// The merchant's brand name (or company name).
            /// </summary>
            public static string BRANDNAME = "BRANDNAME";
            
            /// <summary>
            /// The API Username for authentication.
            /// </summary>
            public static string USER = "USER";
            /// <summary>
            /// The API Password for authentication.
            /// </summary>
            public static string PWD = "PWD";
            /// <summary>
            /// The API Signature for authentication.
            /// </summary>
            public static string SIGNATURE = "SIGNATURE";
            
            /// <summary>
            /// The requested payment amount.
            /// </summary>
            public static string PAYMENTREQUEST_AMT = "PAYMENTREQUEST_AMT";
            public static string DESCRIPTION = "DESCRIPTION";

            public static string FIRSTNAME = "FIRSTNAME";
            public static string LASTNAME = "LASTNAME";
            public static string ADDRESS = "ADDRESS";
            public static string CITY = "CITY";
            public static string STATE = "STATE";
            public static string POSTALCODE = "POSTALCODE";
            public static string COUNTRY = "COUNTRY";

            public static string NAME_ON_CREDIT_CARD = "NAME_ON_CREDIT_CARD";
            public static string CREDIT_CARD_TYPE = "CREDIT_CARD_TYPE";
            public static string CREDIT_CARD_NUMBER = "CREDIT_CARD_NUMBER";
            public static string CREDIT_CARD_EXPDATE = "CREDIT_CARD_EXPDATE";
            public static string CCV2 = "CCV2";

            public static string ERRORCODE = "ERRORCODE";
            public static string SHORTMESSAGE = "SHORTMESSAGE";
            public static string LONGMESSAGE = "LONGMESSAGE";

            /// <summary>
            /// The Id generated after a success payment transaction takes place.
            /// Used by the caller as a reference to tie the payment transaction to an order.
            /// </summary>
            public static string TRANSACTIONID = "TRANSACTIONID";
        }
    }
}
